services:
  swagger:
    environment:
      SWAGGER_JSON: /var/specs/engine-public-api.swagger.json
    image: swaggerapi/swagger-ui
    ports:
      - target: 8080
        published: "9753"
    volumes:
      - source: .
        target: /var/specs
        type: bind
