//
// Copyright 2026 HotelEngine, Inc., d/b/a Engine
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at:
//
//   http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//

syntax = "proto3";

package engine.notification.service.v1;

import "protoc-gen-openapiv2/options/annotations.proto";
import "engine/notification/service/v1/error.proto";

option go_package = "engine.com/engine-partner-api/v1/notification/service";
option java_package = "com.engine.notification.v1.service";
option java_multiple_files = true;

// Requests deletion of an event subscription.
message DeleteSubscriptionRequest {
  option (grpc.gateway.protoc_gen_openapiv2.options.openapiv2_schema) = {
    json_schema: {
      title: "Notification_Service_DeleteSubscriptionRequest_v1"
    }
  };

  // This identifies the subscription to remove as provided by [Subscribe].
  string subscription_id = 1;
}

// Confirms the requested deletion.
message DeleteSubscriptionResponse {}

// Error information returned in the error details of failed [NotificationManagementService.DeleteSubscription] calls.
message DeleteSubscriptionError {
  option (grpc.gateway.protoc_gen_openapiv2.options.openapiv2_schema) = {
    json_schema: {
      title: "Notification_Service_DeleteSubscriptionError_v1"
    }
  };

  oneof error {
    // The requested event subscription does not exist.
    .engine.notification.service.v1.SubscriptionNotFound subscription_not_found = 1;
  }
}
